name: linyora_project
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  # ğŸ‘‡ Ø£Ø¶ÙÙ†Ø§ Ù…ÙƒØªØ¨Ø© Ø§Ù„ØªØ±Ø¬Ù…Ø© Ù‡Ù†Ø§ Ø¯Ø§Ø®Ù„ Ø§Ù„Ù€ dependencies
  flutter_localizations:
    sdk: flutter

  # Ø§Ù„Ø£ÙŠÙ‚ÙˆÙ†Ø§Øª ÙˆØ§Ù„Ù…ÙƒØªØ¨Ø§Øª Ø§Ù„Ø£Ø®Ø±Ù‰
  cupertino_icons: ^1.0.8
  dio: ^5.9.0
  flutter_secure_storage: ^10.0.0
  shared_preferences: ^2.5.3
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.1.1
  video_player: ^2.10.1
  flutter_cache_manager: ^3.4.1
  story_view: ^0.16.6
  percent_indicator: ^4.2.5
  curved_navigation_bar: ^1.0.6
  marquee: ^2.3.0
  visibility_detector: ^0.4.0+2
  preload_page_view: ^0.2.0
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.9.1
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true # ğŸ‘ˆ Ù‡Ø°Ø§ Ø§Ù„Ø³Ø·Ø± Ø¶Ø±ÙˆØ±ÙŠ Ø¬Ø¯Ø§Ù‹ Ù„ØªÙˆÙ„ÙŠØ¯ Ù…Ù„ÙØ§Øª Ø§Ù„ØªØ±Ø¬Ù…Ø©
